[package]
name = "r64emu"
version = "0.1.0"
authors = ["Giovanni Bajo <rasky@develer.com>"]

[dependencies]
emu = {path =  "./emu"}
emu_derive = {path =  "./emu/emu-derive"}
num = "0.1.42"
error-chain = "0.12.0"
pretty-hex = "0.1.0"
slog = "2.2.3"
slog-async = "2.3.0"
slog-term = "2.4.0"
crc = "^1.0.0"
lazy_static = "1.0"
bitflags = "1.0"
bit_field = "0.9.0"
enum-map = "0.4.0"

[dependencies.byteorder]
version = "1"
features = ["i128"]

[profile.dev]
overflow-checks = false
