[package]
name = "emu"
version = "0.1.0"
authors = ["Giovanni Bajo <rasky@develer.com>"]

[dependencies]
byteorder = "1"
enum-map = "0.4.0"
static_assertions = "0.2.5"
num = "0.1.42"
bitflags = "1.0"
array-macro = "1.0"
emu_derive = { path="emu-derive" }
slog-term = "2.4.0"
typenum = "1.10.0"
imgui = "0.0.20"
imgui-sdl2 = "*"
imgui-opengl-renderer = "*"
gl = "0.10.0"

[dependencies.sdl2]
version = "0.31.0"
features = ["static-link","bundled"]

[dependencies.slog]
version = "2.4.1"
features = ["nothreads"]

[patch.crates-io]
"slog" = { path = "../vendor/slog" }
