[package]
name = "emu"
version = "0.1.0"
authors = ["Giovanni Bajo <rasky@develer.com>"]

[dependencies]
byteorder = "1"
enum-map = "0.4.0"
static_assertions = "0.2.5"
num = "0.1.42"
bitflags = "1.0"
array-macro = "1.0"
emu_derive = { path="emu-derive" }
slog = "2.2.3"
