[package]
name = "emu-derive"
version = "0.1.0"
authors = ["Giovanni Bajo <rasky@develer.com>"]

[dependencies]
syn = "0.14"
synstructure = "0.9.0"
quote = "0.6"
proc-macro2 = "0.4"

[lib]
proc-macro = true
